version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.10.3
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__DAGS_FOLDER: /dags
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    depends_on:
      - postgres
    volumes:
      - ./processed_data:/processed_data
      - ./visualizations:/visualizations
      - ./models:/models
      - ./reports:/reports
      - C:/Users/Maciek/Downloads/s24870_Heart_Disease-Projekt-3/dags:/dags
      - ./logs:/logs
      - ./plugins:/opt/airflow/plugins
      - ./credentials.json:/opt/airflow/credentials.json
      - C:/Users/Maciek/Downloads/s24870_Heart_Disease-Projekt-3/requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: >
      bash -c "
        pip install -r /requirements.txt &&
        airflow db init &&
        airflow users create --username admin --password admin --firstname Air --lastname Flow --role Admin --email admin@example.com &&
        airflow webserver
        "

volumes:
  postgres_data:
